### ISSUE TITLE
Sink interface changes for additional sink types. [JIRA: RIAK-2402]

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/riak_pipe#77]
Goals:
- To allow `pg2` and `gproc` to serve as sinks for pipe output. 
  - This allows a group of processes to receive the output of a pipe without having to multiplex through a gen_server.

Proposed changes:
- Deprecate the use of `sink_type` and change `sink` to support tuples describing different adapters for the sink.
- Remove assumptions that the sink will be a Pid.

Proposed changes:
- New type specification for sink:

``` erlang
-type sink() :: {raw, pid()} | 
                    {fsm, pid(), integer(), integer() |
                    {pg2, term()} | 
                    {gproc, gproc:key()}.
```
- `send_to_sink/3` becomes `send_to_sink/2` extension to use `gproc:send/2` or a comprehension over `pg2:get_members/2` 
- Modifications to `riak_pipe:validate_sink_type/2` to collapse into `riak_pipe:ensure_sink/1`.

@hobbyist

**Comment by cmeiklejohn** [comment]
I have part of this implemented already and will take the lead if we like the idea.  This does, however, break backwards compatibility so maybe we want to provide a shim layer for people using `sink_type`.

**Comment by beerriot** [comment]
I remember now where the trickiness is. The sink is represented in the `#fitting_details{}` record by a `#fitting{}` record. It's that record that is insisting on a pid. Sinks are marked by setting the `chashfun` field of that record to `sink`.

The idea behind reusing the `#fitting{}` record was to make any code concerned with the "next" stage mostly polymorphic, save for one place in `riak_pipe_vnode_worker`, where `chashfun` field inspection throws execution to `riak_pipe_sink`.

Keeping every "next" as a `#fitting{}` also makes it possible to use one pipe's first fitting as another's "sink". This is currently used in Riak KV, to set up a key/2i-listing pipe with outputs directed at an MR pipe.

This is all just to say that the incision might have to go a little deeper, perhaps altering the definition of `#fitting{}` or `#fitting_details{}`, and maybe also including `{fitting, #fitting{}}` in the definition of the `sink()` type.

**Comment by bashopatricia** [comment]
No active plans to implement this.  Re-open if prioritized for the roadmap.

**Comment by cmeiklejohn** [comment]
That's a shame, that would have been a good change to have for those of us who have used this library outside of Riak.

**Comment by jonmeredith** [comment]
Agreed, but unfortunately bandwidth is limited.  Pull requests accepted :)
